### ISSUE TITLE
value of type 'JSON' has no member 'isExists'

### ISSUE THREAD

**Issue by AbbyLynn** [Rentlio/SwiftRestModel#10]
Hey, I have a new project I am working on and wanting to integrate SwiftRestModel, but when trying to run the app it is popping up with

> value of type 'JSON' has no member 'isExists'
- Pods/SwiftRestModel/Source/SwiftRestModel.swift:44:22: Value of type 'JSON' has no member 'isExists'

**Comment by jurajhilje** [comment]
Hello Abby! Can you send the code snippet from your app that causes this problem?
What REST method is causing the error?

**Comment by AbbyLynn** [comment]
Hey,

Thanks for quick response. I was attempting to use a GET request but it didnt matter because i could not build the app at all before it failed. As for the exact line i will get it tommorrow.

**Comment by AbbyLynn** [comment]
I quickly glanced at the code on my iPad and i found where it is. So i was integrating it manually.

SwiftRestModel.swift line 44 within the isNew function.

> 
public func isNew() -> Bool {
if (self.data["id"].isExists()) {

**Comment by jurajhilje** [comment]
This is my fault, i need to complete the documentation for manual integration.
If you are using manual integration that's perfectly ok, just include [dependencies](https://github.com/Rentlio/SwiftRestModel#dependencies) (Alamofire, SwiftyJSON and HTTPStatusCodes) in your project and you should be fine.

**Comment by AbbyLynn** [comment]
Awesome! I had all but HTTPSTatusCodes included. I will take a look tomorrow. Insaw that as a dependency but didnt think about it. Still new to ios/swift dev coming frim web dev so. Thanks!!

**Comment by jurajhilje** [comment]
Cool! Let me know if everything is in order.

**Comment by AbbyLynn** [comment]
Alrighty, so I took a look at it and I did already have HTTPStatusCodes imported. Looked into it a little further and was able to figure it out. Looks like just last month SwiftyJSON renamed `isExists` to `exists()`. Changed it in the code and it seems to be working fine now. I created a pull request #11
