### ISSUE TITLE
PATCH method?

### ISSUE THREAD

**Issue by AbbyJanke** [Rentlio/SwiftRestModel#12]
Was just curious if there was a reason of why you are only using PUT instead of PATCH? Generally PUT is used if you are providing details to update every field for that resource where PATCH is a partial. The API I developed I am using POST for new and PATCH for updating, so I am just curious about your decision for this and how you are using it? I could probably come up with something and make a pull request, but just curious about it all.

Thanks :)

**Comment by jurajhilje** [comment]
SwiftRestModel is inspired by Backbone.js where `save()` sends PUT request for existing model.
Although PATCH may be more correct to use, in most APIs that i've used PUT is sent for updating model.

I will leave PUT method as default for `save()`, but will add `method` parameter to it.
Something like this:

`model.save(method: "patch")`
