### ISSUE TITLE
Swift3

### ISSUE THREAD

**Issue by bulteau** [Rentlio/SwiftRestModel#13]
Updated to latest Xcode/Swift

**Comment by skrosoft** [comment]
+1

I think it should use the v4.0 of Alamofire

![image](https://cloud.githubusercontent.com/assets/4645565/18979975/07526036-86a6-11e6-93f1-da5fd9b7f8ea.png)

**Comment by bulteau** [comment]
Exactly ! I try to modify SwiftRestModel.swift file to be compatible with Swift 3. (https://github.com/bulteau/SwiftRestModel3)
I didn't test it a lot.

**Comment by jurajhilje** [comment]
Yes, Xcode 8/Swift 3 update coming soon.

**Comment by jurajhilje** [comment]
Update:
Got everything working locally with Xcode 8 and Swift 3.
Just need to get Travis CI to play nice with xcode8 osx_image. Hang tight!

**Comment by skrosoft** [comment]
This thread shoud be closed, swift 3 version of this project is working fine.

**Comment by jurajhilje** [comment]
Travis CI is giving me a hard time. It will be merged and pushed to CocoaPods as soon as i resolve that.

**Comment by jurajhilje** [comment]
SwiftRestModel (2.0.4) with support for Xcode 8 and Swift 3 is published to CocoaPods. #17
